### ISSUE TITLE
1.20.1 version disconnects all players with "Invalid player data" (not tested on 1.20.2)

### ISSUE THREAD

**Issue by williamistGitHub** [YukkuriLaboratory/FabSit#2]
Whenever the 1.20.1 version of the mod (from the 1.20.1 branch) is installed on a server and a player joins, this errors occurs and the player is kicked with the message "Invalid player data". This seems to be some sort of issue with a mixin, but I'm not an expert on those so I'm not sure if I can fix it.
```
java.lang.ClassCastException: class net.fabricmc.fabric.impl.registry.sync.packet.DirectRegistryPacketHandler cannot be cast to class net.fill1890.fabsit.mixin.accessor.ServerPlayNetworkHandlerAccessor (net.fabricmc.fabric.impl.registry.sync.packet.DirectRegistryPacketHandler and net.fill1890.fabsit.mixin.accessor.ServerPlayNetworkHandlerAccessor are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @29ee9faa)
	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.handler$bfp000$fabsit$removeFromSync(RegistrySyncManager.java:543) ~[fabric-registry-sync-v0-2.3.2+4df89eb277-3830ec6d52dbef83.jar:?]
	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.sendPacket(RegistrySyncManager.java:89) ~[fabric-registry-sync-v0-2.3.2+4df89eb277-3830ec6d52dbef83.jar:?]
	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.sendPacket(RegistrySyncManager.java:82) ~[fabric-registry-sync-v0-2.3.2+4df89eb277-3830ec6d52dbef83.jar:?]
	at net.fabricmc.fabric.impl.registry.sync.FabricRegistryInit.lambda$onInitialize$0(FabricRegistryInit.java:30) ~[fabric-registry-sync-v0-2.3.2+4df89eb277-3830ec6d52dbef83.jar:?]
	at net.fabricmc.fabric.api.networking.v1.ServerPlayConnectionEvents.lambda$static$2(ServerPlayConnectionEvents.java:48) ~[fabric-networking-api-v1-1.3.10+eeb8eb3677-5f0732b3ac824797.jar:?]
	at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.onClientReady(ServerPlayNetworkAddon.java:66) ~[fabric-networking-api-v1-1.3.10+eeb8eb3677-5f0732b3ac824797.jar:?]
	at net.minecraft.class_3324.handler$bdc000$fabric-networking-api-v1$handlePlayerConnection(class_3324.java:4518) ~[server-intermediary.jar:?]
	at net.minecraft.class_3324.method_14570(class_3324.java:215) ~[server-intermediary.jar:?]
	at net.minecraft.class_3248.method_33800(class_3248.java:131) ~[server-intermediary.jar:?]
	at net.minecraft.class_3248.method_14384(class_3248.java:118) ~[server-intermediary.jar:?]
	at net.minecraft.class_3248.redirect$bdd000$fabric-networking-api-v1$handlePlayerJoin(class_3248.java:563) ~[server-intermediary.jar:?]
	at net.minecraft.class_3248.method_18784(class_3248.java:68) ~[server-intermediary.jar:?]
	at net.minecraft.class_2535.method_10754(class_2535.java:259) ~[server-intermediary.jar:?]
	at net.minecraft.class_3242.method_14357(class_3242.java:172) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:908) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:283) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by turtton** [comment]
Fixed in 53e82581a217d9af8928f4ea6bd8a98413d2b8b3
